# LAB 5 : DATA CLEANING

In [5]:
import pandas as pd
df = pd.read_csv("dirtydata.csv")
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [6]:
# To get information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [7]:
# Describe the data
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [8]:
# Prints the first ten rows of the data set
print(df.head(10))
print("n")
# Prints the last ten rows of the data set
print(df.tail(10))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1
9        60  '2020/12/10'     98       124     269.0
n
    Duration          Date  Pulse  Maxpulse  Calories
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [9]:
# Convert the dataframe into string
print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [10]:
# Drop NAN(Not A Number) value 
# new_df(new variable) --> stores the values of original data frame and removes nan values  
new_df = df.dropna()
print(new_df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [11]:
# To change the original df
# Use 'inplace=True'
df.dropna(inplace=True)
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [14]:
df.loc[7,'Duration'] = 45
print(df)

    Duration          Date  Pulse  Maxpulse  Calories  duration
0         60  '2020/12/01'    110       130     409.1       NaN
1         60  '2020/12/02'    117       145     479.0       NaN
2         60  '2020/12/03'    103       135     340.0       NaN
3         45  '2020/12/04'    109       175     282.4       NaN
4         45  '2020/12/05'    117       148     406.0       NaN
5         60  '2020/12/06'    102       127     300.0       NaN
6         60  '2020/12/07'    110       136     374.0       NaN
7         45  '2020/12/08'    104       134     253.3      45.0
8         30  '2020/12/09'    109       133     195.1       NaN
9         60  '2020/12/10'     98       124     269.0       NaN
10        60  '2020/12/11'    103       147     329.3       NaN
11        60  '2020/12/12'    100       120     250.7       NaN
12        60  '2020/12/12'    100       120     250.7       NaN
13        60  '2020/12/13'    106       128     345.3       NaN
14        60  '2020/12/14'    104       132     379.3       NaN
15        60  '2020/12/15'     98       123     275.0       NaN
16        60  '2020/12/16'     98       120     215.2       NaN
17        60  '2020/12/17'    100       120     300.0       NaN
19        60  '2020/12/19'    103       123     323.0       NaN
20        45  '2020/12/20'     97       125     243.0       NaN
21        60  '2020/12/21'    108       131     364.2       NaN
23        60  '2020/12/23'    130       101     300.0       NaN
24        45  '2020/12/24'    105       132     246.0       NaN
25        60  '2020/12/25'    102       126     334.5       NaN
26        60      20201226    100       120     250.0       NaN
27        60  '2020/12/27'     92       118     241.0       NaN
29        60  '2020/12/29'    100       132     280.0       NaN
30        60  '2020/12/30'    102       129     380.3       NaN
31        60  '2020/12/31'     92       115     243.0       NaN

In [15]:
# for a larger data set --> where loc of the wrong entry is hard to find
# take index(header) --> store --> x
# increment the value of x
# Till the condition becomes false
for x in df.index:
    # if in the location (x: depends on loop)
    # and duration is > 120
    # in the location x 
    # set he value as 120
    if df.loc[x,"Duration"]>20:
        df.loc[x,"Duration"] = 120

In [16]:
# Delete the value greater than 120
for x in df.index:
    if df.loc[x,"Duration"] > 120:
        df.drop(x,inplace = True)

In [17]:
# Drop the duplicate row 
nv = df.duplicated()

In [18]:
print(nv)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
29    False
30    False
31    False
dtype: bool

In [20]:
# Drop duplicate row
nv = df.duplicated()
new_out = df.loc[nv == True]
print(new_out)
df.drop_duplicates(inplace = True)
print(df.to_string)

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories, duration]
Index: []
<bound method DataFrame.to_string of     Duration          Date  Pulse  Maxpulse  Calories  duration
0        120  '2020/12/01'    110       130     409.1       NaN
1        120  '2020/12/02'    117       145     479.0       NaN
2        120  '2020/12/03'    103       135     340.0       NaN
3        120  '2020/12/04'    109       175     282.4       NaN
4        120  '2020/12/05'    117       148     406.0       NaN
5        120  '2020/12/06'    102       127     300.0       NaN
6        120  '2020/12/07'    110       136     374.0       NaN
7        120  '2020/12/08'    104       134     253.3      45.0
8        120  '2020/12/09'    109       133     195.1       NaN
9        120  '2020/12/10'     98       124     269.0       NaN
10       120  '2020/12/11'    103       147     329.3       NaN
11       120  '2020/12/12'    100       120     250.7       NaN
13       120  '2020/12/13'    106       128     345.3       NaN
14       120  '2020/12/14'    104       132     379.3       NaN
15       120  '2020/12/15'     98       123     275.0       NaN
16       120  '2020/12/16'     98       120     215.2       NaN
17       120  '2020/12/17'    100       120     300.0       NaN
19       120  '2020/12/19'    103       123     323.0       NaN
20       120  '2020/12/20'     97       125     243.0       NaN
21       120  '2020/12/21'    108       131     364.2       NaN
23       120  '2020/12/23'    130       101     300.0       NaN
24       120  '2020/12/24'    105       132     246.0       NaN
25       120  '2020/12/25'    102       126     334.5       NaN
26       120      20201226    100       120     250.0       NaN
27       120  '2020/12/27'     92       118     241.0       NaN
29       120  '2020/12/29'    100       132     280.0       NaN
30       120  '2020/12/30'    102       129     380.3       NaN
31       120  '2020/12/31'     92       115     243.0       NaN>

In [33]:
import pandas as pd 
import numpy as np
# Dictionary
dict = {'First Score' : [100,90,np.nan,95],
        'Second score' : [np.nan, 45,56,np.nan],
        'Third Score' : [np.nan, 40,80,98]
       }
df = pd.DataFrame(dict)
print(df)

   First Score  Second score  Third Score
0        100.0           NaN          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [26]:
print(df.to_string)
# Return true if null and false if not null
print(df.isnull())
# Return true if not null and false if null
print(df.notnull())

<bound method DataFrame.to_string of    First Score  Second score  Third Score
0        100.0           NaN          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0>
   First Score  Second score  Third Score
0        False          True         True
1        False         False        False
2         True         False        False
3        False          True        False
   First Score  Second score  Third Score
0         True         False        False
1         True          True         True
2        False          True         True
3         True         False         True

In [30]:
# Fill the value with a specific value 
print(df.fillna(0))

   First Score  Second score  Third Score
0        100.0           0.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [34]:
# Fill the NaN value with mean
df_mean = df.mean()
print(df_mean)
data_new = df.fillna(df.mean())
print(data_new)

First Score     95.000000
Second score    50.500000
Third Score     72.666667
dtype: float64
   First Score  Second score  Third Score
0        100.0          50.5    72.666667
1         90.0          45.0    40.000000
2         95.0          56.0    80.000000
3         95.0          50.5    98.000000

In [50]:
df2 = pd.read_csv("my_file (1).csv")
print(df2)

    Rank   Peak All Time Peak     Actual gross  \
0      1      1             2     $780,000,000
1      2      1          7[2]     $579,800,000
2      3   1[4]          2[5]     $411,000,000
3      4   2[7]         10[7]     $397,300,000
4      5   2[4]           NaN     $345,675,146
5      6   2[4]         10[9]     $305,158,363
6      7  2[10]           NaN     $280,000,000
7      7    NaN           NaN     $257,600,000
8      9    NaN           NaN     $256,084,556
9     10    NaN           NaN     $250,400,000
10    11    NaN           NaN  $229,100,000[b]
11    12    NaN        14[17]     $227,400,000
12    13    NaN           NaN     $204,000,000
13    14  1[20]           NaN     $200,000,000
14    15   2[c]           NaN     $194,000,000
15    16    NaN           NaN     $184,000,000
16    17    NaN           NaN     $170,000,000
17    18    NaN           NaN     $169,800,000
18    19    NaN           NaN  $167,700,000[e]
19    20    NaN           NaN     $150,000,000

   Adjusted gross (in 2022 dollars)        Artist  \
0                      $780,000,000  Taylor Swift
1                      $579,800,000       Beyoncé
2                      $560,622,615       Madonna
3                      $454,751,555          Pink
4                      $402,844,849  Taylor Swift
5                      $388,978,496       Madonna
6                      $381,932,682   Celine Dion
7                      $257,600,000          Pink
8                      $312,258,401       Beyoncé
9                      $309,141,878  Taylor Swift
10                     $283,202,896       Beyoncé
11                     $295,301,479     Lady Gaga
12                     $251,856,802    Katy Perry
13                     $299,676,265          Cher
14                     $281,617,035       Madonna
15                     $227,452,347          Pink
16                     $213,568,571     Lady Gaga
17                     $207,046,755       Madonna
18                     $204,486,106         Adele
19                     $185,423,109  Taylor Swift

                                  Tour title    Year(s)  Shows Average gross  \
0                            The Eras Tour †  2023–2024     56   $13,928,571
1                     Renaissance World Tour       2023     56   $10,353,571
2                Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3                Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4                    Reputation Stadium Tour       2018     53    $6,522,173
5                              The MDNA Tour       2012     88    $3,467,709
6                  Taking Chances World Tour  2008–2009    131    $2,137,405
7                          Summer Carnival †  2023–2024     41    $6,282,927
8                   The Formation World Tour       2016     49    $5,226,215
9                        The 1989 World Tour       2015     85    $2,945,882
10           The Mrs. Carter Show World Tour  2013–2014    132    $1,735,606
11                   The Monster Ball Tour *  2009–2011    203    $1,118,227
12                      Prismatic World Tour  2014–2015    151    $1,350,993
13  Living Proof: The Farewell Tour ‡[21][a]  2002–2005    325      $615,385
14                          Confessions Tour       2006     60    $3,233,333
15                 The Truth About Love Tour  2013–2014    142    $1,295,775
16                        Born This Way Ball  2012–2013     98    $1,734,694
17                          Rebel Heart Tour  2015–2016     82    $2,070,732
18                           Adele Live 2016  2016–2017    121    $1,385,950
19                              The Red Tour  2013–2014     86    $1,744,186

        Ref.
0        [1]
1        [3]
2        [6]
3        [7]
4        [8]
5        [9]
6       [11]
7       [12]
8       [13]
9       [14]
10  [15][16]
11      [18]
12      [19]
13      [20]
14       [5]
15      [22]
16       [d]
17       [4]
18      [25]
19      [26]

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [37]:
df.describe()

       First Score  Second score  Third Score
count          3.0      2.000000     3.000000
mean          95.0     50.500000    72.666667
std            5.0      7.778175    29.687259
min           90.0     45.000000    40.000000
25%           92.5     47.750000    60.000000
50%           95.0     50.500000    80.000000
75%           97.5     53.250000    89.000000
max          100.0     56.000000    98.000000

In [43]:
print(df2.to_string())

    Rank   Peak All Time Peak     Actual gross Adjusted gross (in 2022 dollars)        Artist                                Tour title    Year(s)  Shows Average gross      Ref.
0      1      1             2     $780,000,000                     $780,000,000  Taylor Swift                           The Eras Tour †  2023–2024     56   $13,928,571       [1]
1      2      1          7[2]     $579,800,000                     $579,800,000       Beyoncé                    Renaissance World Tour       2023     56   $10,353,571       [3]
2      3   1[4]          2[5]     $411,000,000                     $560,622,615       Madonna               Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294       [6]
3      4   2[7]         10[7]     $397,300,000                     $454,751,555          Pink               Beautiful Trauma World Tour  2018–2019    156    $2,546,795       [7]
4      5   2[4]           NaN     $345,675,146                     $402,844,849  Taylor Swift                   Reputation Stadium Tour       2018     53    $6,522,173       [8]
5      6   2[4]         10[9]     $305,158,363                     $388,978,496       Madonna                             The MDNA Tour       2012     88    $3,467,709       [9]
6      7  2[10]           NaN     $280,000,000                     $381,932,682   Celine Dion                 Taking Chances World Tour  2008–2009    131    $2,137,405      [11]
7      7    NaN           NaN     $257,600,000                     $257,600,000          Pink                         Summer Carnival †  2023–2024     41    $6,282,927      [12]
8      9    NaN           NaN     $256,084,556                     $312,258,401       Beyoncé                  The Formation World Tour       2016     49    $5,226,215      [13]
9     10    NaN           NaN     $250,400,000                     $309,141,878  Taylor Swift                       The 1989 World Tour       2015     85    $2,945,882      [14]
10    11    NaN           NaN  $229,100,000[b]                     $283,202,896       Beyoncé           The Mrs. Carter Show World Tour  2013–2014    132    $1,735,606  [15][16]
11    12    NaN        14[17]     $227,400,000                     $295,301,479     Lady Gaga                   The Monster Ball Tour *  2009–2011    203    $1,118,227      [18]
12    13    NaN           NaN     $204,000,000                     $251,856,802    Katy Perry                      Prismatic World Tour  2014–2015    151    $1,350,993      [19]
13    14  1[20]           NaN     $200,000,000                     $299,676,265          Cher  Living Proof: The Farewell Tour ‡[21][a]  2002–2005    325      $615,385      [20]
14    15   2[c]           NaN     $194,000,000                     $281,617,035       Madonna                          Confessions Tour       2006     60    $3,233,333       [5]
15    16    NaN           NaN     $184,000,000                     $227,452,347          Pink                 The Truth About Love Tour  2013–2014    142    $1,295,775      [22]
16    17    NaN           NaN     $170,000,000                     $213,568,571     Lady Gaga                        Born This Way Ball  2012–2013     98    $1,734,694       [d]
17    18    NaN           NaN     $169,800,000                     $207,046,755       Madonna                          Rebel Heart Tour  2015–2016     82    $2,070,732       [4]
18    19    NaN           NaN  $167,700,000[e]                     $204,486,106         Adele                           Adele Live 2016  2016–2017    121    $1,385,950      [25]
19    20    NaN           NaN     $150,000,000                     $185,423,109  Taylor Swift                              The Red Tour  2013–2014     86    $1,744,186      [26]

In [53]:
df2.dropna(inplace=True)
print(df2)

   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
5     6  2[4]         10[9]  $305,158,363                     $388,978,496

         Artist                   Tour title    Year(s)  Shows Average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
5       Madonna                The MDNA Tour       2012     88    $3,467,709

  Ref.
0  [1]
1  [3]
2  [6]
3  [7]
5  [9]

In [54]:
print(df2.to_string())

   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)        Artist                   Tour title    Year(s)  Shows Average gross Ref.
0     1     1             2  $780,000,000                     $780,000,000  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571  [1]
1     2     1          7[2]  $579,800,000                     $579,800,000       Beyoncé       Renaissance World Tour       2023     56   $10,353,571  [3]
2     3  1[4]          2[5]  $411,000,000                     $560,622,615       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294  [6]
3     4  2[7]         10[7]  $397,300,000                     $454,751,555          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795  [7]
5     6  2[4]         10[9]  $305,158,363                     $388,978,496       Madonna                The MDNA Tour       2012     88    $3,467,709  [9]

In [55]:
# Drop duplicate row
nv = df2.duplicated()
new_out = df2.loc[nv == True]
print(new_out)
df2.drop_duplicates(inplace = True)
print(df2.to_string)

Empty DataFrame
Columns: [Rank, Peak, All Time Peak, Actual gross, Adjusted gross (in 2022 dollars), Artist, Tour title, Year(s), Shows, Average gross, Ref.]
Index: []
<bound method DataFrame.to_string of    Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
5     6  2[4]         10[9]  $305,158,363                     $388,978,496

         Artist                   Tour title    Year(s)  Shows Average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
5       Madonna                The MDNA Tour       2012     88    $3,467,709

  Ref.
0  [1]
1  [3]
2  [6]
3  [7]
5  [9]  >

In [67]:
# Take the user input for dropping of any column
# df = df.drop(columns = 'column_name')
# drop mutiple (columns = ['col1','col2',.....])
print(df2)
ip = input("Enter the column to drop : ")
print(ip)
new_df2 = df2.drop(columns = ip)
print(new_df2)

   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
5     6  2[4]         10[9]  $305,158,363                     $388,978,496

         Artist                   Tour title    Year(s)  Shows Average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
5       Madonna                The MDNA Tour       2012     88    $3,467,709

  Ref.
0  [1]
1  [3]
2  [6]
3  [7]
5  [9]

Enter the column to drop :  Tour title

Tour title
   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
5     6  2[4]         10[9]  $305,158,363                     $388,978,496

         Artist    Year(s)  Shows Average gross Ref.
0  Taylor Swift  2023–2024     56   $13,928,571  [1]
1       Beyoncé       2023     56   $10,353,571  [3]
2       Madonna  2008–2009     85    $4,835,294  [6]
3          Pink  2018–2019    156    $2,546,795  [7]
5       Madonna       2012     88    $3,467,709  [9]